### ISSUE TITLE
Support IFFR 2021

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#127]
## Requirements
- [x] Read titles and URL's
- [x] Read descriptions and articles
- [x] Read screened films of combination programs
- [x] Support testing in the planner (screeningless mode) => Split off to #164
- [x] Get all available film sites off-line
- [x] Import into the planner as to rate the films
- [x] Be prepared for on-line streamings
- [x] Fix overlapping screenings on screen "Online"
- [x] Fix disappeared durations
- [x] Fix navigation problems => Split off to #143
- [x] Exclude industry screenings
- [x] Handle 'Met voorfilm & live Q&A'

### Split-off's
- Support (on-line) screening windows of more than 24 hours #158
