### ISSUE TITLE
Create all Film Info data in loader

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#139]
## Motivation
Festival sites change each year, and so do the loader scripts. This includes the information we collect describing the films.
Although planning can start faster when skipping to extract the extra information, it's still undesirable to change the planner every year to suit new web sites.
A way to fight the risk that titles change and screenings need other film ID's, is to be able to call the `python` functions from inside `C#`.
## Requirements
Solved in #150.
- [x] All Film Info attributes (Description, Article and, for compilations, Screened Films) are all filled in the loader project
- [x] Download Film Info view is superfluous
- [x] Download Film Info view is decommissioned
