### ISSUE TITLE
Automatic planning

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#18]
- [x] At first as simple as possible
- [x] Prefer friend attended screenings
- [x] Take already attended films into account
- [x] Prefer same-rated film with least screenings in case of overlap in time
- [x] Mark automatically assigned screenings as such #95
- [x] Possibility to undo planning (only screenings marked as auto-planned)
- [x] Possibility to list screenings from the Not Planned Films list
- [x] Film description in Not Planned Films list
- [x] Consider travel time
- [x] Possibility to list screenings from the ~High Rated~ _Not Planned_ Films list
- [x] Film description in ~High Rated~ _Not Planned_  Films list

Checked means that a user story is created.

**Comment by maar35** [comment]
## Done
## Closing Epic
`epic` stories will be closed, since Milestones do more or less the same, in a better way.
