### ISSUE TITLE
Improve testability between python and C# projects

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#20]
### Objective
Preserve information that is manually added in the (`C#`) Planner when re-running the (`python`) Loader.

### Principles
- [x] Separate data from Loader from manually added information
- [x] Link manually added information to Loader data using keys that are independent of reloading

### Refinement decisions
- [x] Decide on unique key strategy
- [x] Decide how to maintain the `FilmInfoStatus` property =>
  - Maintain `FilmInfoStatus` in class `FilmInfo`
  - Field `Url` to be moved from `FilmInfo` to `Film` (primarily maintained in the loader now)

#### Film info status maintenance
Update class `FilmInfo` information (in XML) in `python`? => No, everything from Python is Loader Information and belongs in class `Film`, `Screening` etc.

### Create user stories
- [x] Maintain `C#` and `python` code in one repository #17
- [x] Take editable fields from class `Screening` #10, #43 
- [x] Take editable fields from class `Film` #8, #25
- [x] Change the loader (`python`) `write` functions as to match the planner (`C#`) `read` functions #39 
- [x] Loader should read back films list to preserve numbering
