### ISSUE TITLE
Subsection in films list

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#292]
## Requirements
- [x] New app `section`
- [x] Model `Section`
- [x] Model `Subsection`
- [x] Migration plan
- [x] Execute migration plan
- [x] Add tests
- [x] Update documentation

### Migration plan
- [x] Allow loading films with and without valid link to subsection
- [x] Migrate `Section` and `Subsection`
- [x] View to load sections and subsections
- [x] Rename `Film.section` into `subsection`
- [x] Method to find subsection when present
- [x] Load sections and subsections for all festivals that support it
- [x] Display subsection in the film properties list in the `film_list:results` page
- [x] Display subsection in the film ratings list in the `film_list:film_list` page
- [x] Color the displayed subsection with de corresponding sector color (in the rating list)

#### Tasks split off to #302
- Allow loading films with and without valid link to subsection
- Redefine `Film.subsection` as foreign key, nullable, on delete set null, consider `db_constraint=False`
- View to reload films when support for subsections is realized
- Decommission the method to find subsection when present

**Comment by maar35** [comment]
## Requirements
- [ ] New app `section`
- [ ] Model `Section`
- [ ] Model `Subsection`
- [ ] Migration plan
- [ ] Execute migration plan

### Migration plan
- [ ] Allow loading films with and without valid link to subsection
- [ ] View to load sections and subsections
- [ ] Method to find subsection when present
- [ ] Migrate `Section` and `Subsection`
- [ ] Load sections and subsections for all festivals that support it
- [ ] Rename `Film.section` into `subsection`
- [ ] Redefine `Film.subsection` as foreign key, nullable, on delete set null, consider `db_constraint=False`
- [ ] View to reload films when support for subsections is realized
