### ISSUE TITLE
Upgrade Python and Django

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#356]
## Overview
Target is to upgrade Python from `3.8.5` to `3.12`.
Django should be upgraded from `3.2.9` to `4.2.8` (an [LTS](https://docs.djangoproject.com/en/5.0/internals/release-process/#term-Long-term-support-release) release), the oldest version that supports Python `3.12`.

## Implementation Plan
To mitigate the announced deprecations, a possible fist step is to upgrade Python to `3.10`, which is supported by Django `4.0` and `4.2.8`
### Implementation steps
- [x] Backup the data
- [x] Upgrade Django to `4.0.10`
- [x] Test and fix
- [x] Upgrade Python to `3.10.14`
- [x] Test and fix
- [x] Upgrade Django to `4.2.8` (via `4.1.13`)
- [x] Test and fix
- [x] Upgrade Python to `3.12.3`
- [x] Test and fix
- [x] Update some fun stuff using the new possibilities

### Links
[What Python version can I use with Django?](https://docs.djangoproject.com/en/5.0/faq/install/#faq-python-version-support)
[What is new in Python 3.10](https://docs.python.org/3/whatsnew/3.10.html)
[What is new in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html)
[What is new in Django 4.0](https://docs.djangoproject.com/en/5.0/releases/4.0/#top)
[What is new in Django 4.2](https://docs.djangoproject.com/en/5.0/releases/4.2/)
[Upgrade Django to a newer version](https://docs.djangoproject.com/en/5.0/howto/upgrade-version/)

## Requirements
- [x] Cleanup the tests
- [x] Execute migration plan
