### ISSUE TITLE
Advanced automatic planning

### ISSUE THREAD

**Issue by maar35** [maar35/film-festival-planner#94]
## Closing Epic
`epic` stories will be closed, since Milestones do more or less the same, in a better way.

## Underlying User Stories
- [ ] Create one program for multiple film fans #88
- [ ] Consider travel time between theaters #93
- [x] Outline view to analyse not planned films #92
- [x] Allow to accept marked screenings #87
- [x] Maintain availability #47
- [ ] Consider availability #48
- [ ] Optimise number of screenings #89
- [ ] Save a program #90
- [ ] Let user configure sort order of selection criteria #91
- [ ] Improve analyser #103
